### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by Mrtangji** [Souloco/StarRail-FastRun#1]
torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: ''If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
torch\_jit_internal.py:853: UserWarning: Unable to retrieve source for @torch.jit._overload function: <function _DenseLayer.forward at 0x0000018BF5D5FEC0>.
  warnings.warn(
torch\_jit_internal.py:853: UserWarning: Unable to retrieve source for @torch.jit._overload function: <function _DenseLayer.forward at 0x0000018BF5D84D60>.
  warnings.warn(
torchvision\__init__.py:25: UserWarning: You are importing torchvision within its own root folder (E:\StarRail-FastRun). This is not expected to work and may give errors. Please exit the torchvision project source and relaunch your python interpreter.

**Comment by Souloco** [comment]
你可以忽略这段报错，这是用auto-py-to-exe打包导致的问题,程序可以正常使用
You can ignore this error message. This is a problem caused by packaging with auto-py to exe, and the program can be used normally

**Comment by Mrtangji** [comment]
忽略不了啊 gui.exe程序不能运行

**Comment by Mrtangji** [comment]
1.1.5还是不能执行，编译有问题吗 有没有群，另外包体积真的很大。

**Comment by Souloco** [comment]
你可以加入QQ群:906995514

**Comment by Souloco** [comment]
包体体积大我没能力更改，你可以使用源码来减小体积

**Comment by mengchen0601** [comment]
> 你可以加入QQ群:906995514

这个号码搜索显示没有结果

**Comment by Souloco** [comment]
重新搜索
