### ISSUE TITLE
走偏时如果交互到锚点会停在回复界面

### ISSUE THREAD

**Issue by AutoGreat** [Souloco/StarRail-FastRun#10]
- 问题： 后续路线（包括重跑）无法继续
- 是否可以考虑增加容错，类似战斗失败时自动关闭此类界面

![map_4-3_4---43-f](https://github.com/Souloco/StarRail-FastRun/assets/144865652/58f8d249-5bb8-4a45-9912-d91491cbccdd)

**Comment by Souloco** [comment]
后续版本会尽快解决此问题
