### ISSUE TITLE
fastrun时会卡在白日梦酒店梦境的鸟这里，传送出来以后会跟鸟对话导致流程卡住

### ISSUE THREAD

**Issue by smallmj** [Souloco/StarRail-FastRun#15]
![屏幕截图 2024-02-28 124742](https://github.com/Souloco/StarRail-FastRun/assets/23742160/803260a0-dda7-46dc-910b-38d33e28438f)

**Comment by smallmj** [comment]
又在另一个号上跑了一下，发现是传送到这个鸟旁边的传送点后，跑去坐电梯时会跑过，导致后续无法流程无法正常进行，然后一通瞎跑以后，要不然跟这个鸟对话，要不然跟传送点对话，导致后面流程全部卡住

**Comment by Souloco** [comment]
你指的是酒店-4路线吗，能否说明锄大地使用的角色

**Comment by smallmj** [comment]
两个号分别用了布洛尼亚和佩拉，布洛尼亚是卡在跟鸟对话，佩拉是卡在跟传送点互动的界面了

**Comment by Souloco** [comment]
路线已改进,我会关闭此问题,如果还是出现请再次反馈
