### ISSUE TITLE
Fastrun时勾选了吃秘技药，但是全程好像都没有吃过

### ISSUE THREAD

**Issue by smallmj** [Souloco/StarRail-FastRun#17]

**Comment by Souloco** [comment]
秘技食物功能正常使用，自己看看食物数量是否减少

**Comment by smallmj** [comment]
没有减少…而且我发现我明明勾选了吃药，也点了保存了，但是退出gui.exe再打开,吃药的选项又变成没有勾选的状态

**Comment by Souloco** [comment]
你是否有点确定来应用来选择的配置吗

**Comment by smallmj** [comment]
是点确定保存配置还是点保存才能保存配置？

**Comment by smallmj** [comment]
试了很多次，不管是点确定，还是点保存，只要是关了gui.exe再重新打开，吃药选项就自动变回未勾选的状态了

**Comment by Souloco** [comment]
确实有这个BUG下个版本我会修复

**Comment by Souloco** [comment]
V1.9.6版本已修复
