### ISSUE TITLE
建议调整多功能执行时委托的执行顺序

### ISSUE THREAD

**Issue by smallmj** [Souloco/StarRail-FastRun#21]
设定的每天凌晨4点自动执行全流程，如果做的是20个小时的委托，凌晨4点领取，需要前一天早上8点开始委托任务。然而，8点的时候一般锄大地还在进行，等到可以手动设定委托的时候，一般已经9点以后，导致第二天的自动领取委托任务依旧无法按时进行。
建议将委托任务设定在锄大地之后进行或者在前后各执行一遍委托任务。

**Comment by Souloco** [comment]
V1.9.8版本已解决此问题
