### ISSUE TITLE
执行清体力虚无之蕾·大矿区识别超时

### ISSUE THREAD

**Issue by yori2** [Souloco/StarRail-FastRun#28]
09:19:21 |INFO| dungeon.start:108 - 清体力---开始
09:19:21 |INFO| dungeon.start:111 - 清体力---执行副本虚无之蕾·大矿区---24
09:19:21 |INFO| calculated.check_main_interface:551 - 强制在主界面
09:19:55 |INFO| calculated.dungeon_img_click:193 - 识别超时
检查发现是材料图片问题，替换图片后可以正常运行

**Comment by yori2** [comment]
我上传图片老是失败，，，所以就不传啦，麻烦作者可以自己检查一下

**Comment by Souloco** [comment]
V2.2.8版本已重新截图,之前版本我个人使用是可以识别的
