### ISSUE TITLE
清体力行迹材料部分图片编号错误

### ISSUE THREAD

**Issue by yori2** [Souloco/StarRail-FastRun#30]
<img width="945" alt="屏幕截图 2024-05-21 151131" src="https://github.com/Souloco/StarRail-FastRun/assets/87350930/60b12364-044a-4e1b-bc06-cd5fff6e781c">
清体力行迹材料部分图片编号错误太多la，我说最近几天都在刷但是行迹材料没见涨。。。原来这几天全都刷错了

**Comment by Souloco** [comment]
已在V2.3.9版本修复
