### ISSUE TITLE
FastStart无法按日期清体力

### ISSUE THREAD

**Issue by ZHalley** [Souloco/StarRail-FastRun#32]
FastStart.py [line 40]
`sra.dungeon.dungeon_list = dungeon_time[today_id]`
应为
`sra.dungeon.dungeon_list = get_config(dungeon_time[today_id])`

该错误会导致无法按日期清体力

**Comment by Souloco** [comment]
会在下个版本修复

**Comment by Souloco** [comment]
已在V2.4.2版本修复
