### ISSUE TITLE
请问地图线路有自助录制脚本吗？

### ISSUE THREAD

**Issue by Klamist** [Souloco/StarRail-FastRun#7]
请问大佬，这个版本的map的json有录制脚本吗？我在用自己魔改的最初那项目里面的record脚本，感觉转向或起步之类经常会有较大误差……

**Comment by Souloco** [comment]
暂时没有，我录制也是有偏差，需要调整数值

**Comment by Klamist** [comment]
了解。多谢大佬。那我自己多调调。
