### ISSUE TITLE
发现一些奇怪的疾跑bug，导致路线走歪

### ISSUE THREAD

**Issue by Klamist** [Souloco/StarRail-FastRun#8]
应该不是脚本的问题。

1. 赶路时直角转弯的冲刺状态一般会保留，一直维持疾跑转弯。但有时会顿一下，应该是两个方向键的衔接空了一点，导致丢失了一下疾跑状态，会导致预定路线转弯阶段走歪。不过发生率很低。

2. 通常情况，静止时按住shift然后按方向键，会经历开始移动-开始冲刺，也就是有个起步阶段。但极少数情况下，是直接以疾跑速度起步，导致第一段路程走多了。在梦境地图里偶尔发生，并且概率不是很低。
看录像的时候发现的：4-3-7结束去4-4-1（酒店梦境-8），直接原地开始疾跑起步，导致拐弯的时候已经跑过头了。
![4-4-1起步前](https://github.com/Souloco/StarRail-FastRun/assets/33776012/3dc87dfe-bac1-4854-a82c-02ba442b1dcf)
![4-4-1起步突然](https://github.com/Souloco/StarRail-FastRun/assets/33776012/a2025de3-b3b7-4eb5-9584-ea0021800d66)
可以看到刚移动就有疾跑气流。

第一个转弯断疾跑的问题感觉没啥好方法，看了脚本的operate_list和move部分，感觉也没法再快了……只能通过路线里多撞墙弥补意外，不过跑了全程录像里只有3个地方因为这个问题坏掉，其他时候偶尔坏了但也能兼容，感觉忽略吧。

第二个问题多测试了一顿，目前似乎只有传送落地后的起步会有这个BUG。正常起步和疾跑bug起步能大概差出0.15秒的疾跑距离（梦境酒店立体房间的入口发光门的2/3扇门宽度）目前我调成了刚好有没有疾跑BUG都能过门的距离……

**Comment by Souloco** [comment]
我已知晓，我暂时没什么想法对此有针对性的改善

**Comment by kevinchow9527** [comment]
> 我已知晓，我暂时没什么想法对此有针对性的改善

你好，请问锄大地进战斗不自动是什么原因

**Comment by Souloco** [comment]
游戏设置自己设置自动战斗

**Comment by kevinchow9527** [comment]
> 游戏设置自己设置自动战斗

sorry，我没找到设置方法
